apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.groups.type }}
  ports:
    {{- toYaml .Values.service.groups.ports | nindent 3 }}
  selector:
    app: {{ .Release.Name }}
